### ISSUE TITLE
Deck menu shaking

### ISSUE THREAD

**Issue by CuriosusTuberosum** [my-Anki/Beautify-Anki#43]
**Before posting, please verify that you've done the following** 
* [x] read the ["before you install instructions"](https://beautify-anki.shorouk.dev/before-install) and disabled all the known conflicted add-ons.
* [x] You've looked through previous issues to see if someone else had the same problem.

**Describe the bug**
Deck menu is shaking. The shaking is way faster than the recorded gif.

**Screenshots**
![shaky](https://user-images.githubusercontent.com/61952048/97454758-c8f3ff80-193f-11eb-8f1b-a0beadc379c1.gif)

**Contex (please complete the following information):**
 - OS: [Windows 10]
 - Anki Version [2.1.29]
 - screen Resolution [1366x768]

**Additional context**
In your Anki 
go to help > About > Copy Debug Log and paste it between the following backticks 

```
    
    Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-10-28 15:29:28
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['BeautifyAnki', 0, 'None', mod]
    Add Table ['1237621971', 2020-07-25T14:19, 'None', mod]
    Anki Simulator ['817108664', 2020-07-21T16:17, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T02:20, 'v1.1.3', '']
    Auto Ease Factor ['1672712021', 2020-10-19T03:25, 'None', mod]
    Blitzkrieg II - Advanced Browser Sidebar BETA8 ['564851917', 2020-04-17T05:53, 'None', '']
    Browser MaximizeHide TableEditor ['1819291495', 2020-07-03T00:51, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2020-07-08T01:44, 'None', '']
    Clickable Tags v11 ['380714095', 2020-03-22T15:56, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2019-12-25T09:32, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2020-09-02T06:53, 'None', mod]
    Directly review without going through overview page ['1024346707', 2019-11-07T10:36, 'None', '']
    Edit Field During Review Cloze ['385888438', 2020-06-11T14:32, 'None', '']
    Fastbar- with nightmode support ['46611790', 2020-03-20T16:34, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T06:12, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    Links between notes cards to open browser and previewer ['1126950429', 2020-04-07T15:43, 'None', mod]
    Media Import ['1531997860', 2019-12-04T01:17, 'None', '']
    Mini Format Pack ['295889520', 2019-12-04T01:03, 'None', '']
    No Distractions Full Screen Clean review interface  TabletTouch support ['1049863218', 2020-08-14T00:59, 'v4.1.8', mod]
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T08:26, 'None', '']
    Quick Colour Changing ['2491935955', 2017-08-28T14:48, 'None', mod]
    Quick Field Navigation ['734297936', 2019-12-30T04:24, 'None', '']
    ReMemorize Rescheduler with sibling and logging v140 ['323586997', 2020-04-17T09:07, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2020-02-17T19:35, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    Search and Replace Tags ['138501288', 2019-12-04T01:10, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2020-10-25T14:23, 'None', mod]
    Special Fields ['1102281552', 2020-08-16T17:18, 'None', '']
    Symbols As You Type ['2040501954', 2020-04-30T16:32, 'None', '']
    Tag Entry Enhancements ['1348430474', 2019-12-06T15:39, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-18T00:33, 'None', mod]
    True Retention ['613684242', 2019-12-04T01:00, 'None', '']
    extended editor for field for tables searchreplace  ['805891399', 2020-07-30T00:54, 'None', '']
    load balancer ['1417170896', 2020-08-06T01:58, 'None', '']
    scheduler Dynamic Lapse Interval alpha ['678594073', 2020-08-14T11:15, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1024346707 1049863218 1102281552 1126950429 1237621971 1348430474 1374772155 138501288 1417170896 1531997860 1642550423 1672712021 1781298089 1819291495 2040501954 24411424 2491935955 266436365 295889520 323586997 374005964 380714095 385888438 46611790 516643804 538879081 564851917 613684242 678594073 734297936 805891399 817108664 831846358 861263371
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2020-02-04T00:28, 'None', '']
    Advanced Browser ['874215009', 2020-10-04T05:40, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2020-06-09T13:54, 'None', mod]
    AnkiConnect ['2055492159', 2020-07-12T21:54, 'None', '']
    AnkiWebView Inspector ['31746032', 2020-02-15T22:34, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2020-07-12T00:50, 'None', '']
    Batch Editing ['291119185', 2019-12-31T18:13, 'None', '']
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-24T00:03, 'None', '']
    Copy notes ['1566928056', 2020-08-02T18:21, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2020-04-17T23:38, 'None', mod]
    Hint Hotkeys ['1844908621', 2019-12-24T13:04, 'None', '']
    Induction booster ['1885014021', 2020-06-19T04:19, 'None', '']
    Kitten Rewards Gamification ['1627107763', 2020-02-15T22:08, 'None', '']
    Minimize to tray ['85158043', 2020-02-15T17:28, 'None', '']
    Pokemanki ['633922407', 2020-03-04T05:10, 'None', mod]
    Pop-up Dictionary beta ['153625306', 2019-12-04T01:19, 'None', mod]
    Redesign ['1914733489', 2020-03-01T00:46, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-12-05T21:55, 'None', '']
    Spelling Police ['1410276506', 2020-03-03T04:13, 'None', mod]
    TagSelectorV2 ['1022577188', 2020-08-13T05:09, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2020-08-29T20:23, 'None', mod]
    show new siblings in order  no same day spacingrandomization for new siblings ['268644742', 2020-02-18T20:41, 'None', '']

```

**Comment by ShoroukAziz** [comment]
That is really weird. I'll try to regenerate it myself and see what I can do

**Comment by coco1602** [comment]
I have the exact same problem.

**Comment by coco1602** [comment]
![gif](https://user-images.githubusercontent.com/32242384/97976407-f2db7500-1dca-11eb-89a2-1a94f3547811.gif)

**Comment by palosbuenos** [comment]
exact same issue. Happens on windows 10 only and when only beautify is on. Have same system on mac os (same anki version too) and doesnt happen.

    
    Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-12-19 17:32:53
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['Beautify-Anki-master', 0, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['The-KING-of-Button-Add-ons', 0, 'None', mod]
    '' ['reviewer_progress_bar', 0, 'None', '']
    Advanced Browser ['874215009', 2020-11-08T21:33, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2020-07-12T08:20, 'None', '']
    Browser Resizer ['1435775540', 2020-09-08T11:34, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2020-11-18T19:57, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-16T07:31, 'None', mod]
    Edit Field During Review ['1020366288', 2020-10-07T22:52, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T11:51, 'None', '']
    Life Drain ['715575551', 2020-08-13T22:55, 'None', '']
    Mini Format Pack ['295889520', 2018-07-25T03:15, 'None', mod]
    Multi-Line Type Answer Box ['681236951', 2020-08-21T16:04, 'None', '']
    Puppy Reinforcement ['1722658993', 2020-03-03T06:53, 'None', '']
    Resize images in editor ['1103084694', 2020-08-02T22:34, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T22:53, 'None', '']
    Symbols ['1461102936', 2019-04-19T05:51, 'None', mod]

**Comment by palosbuenos** [comment]
Update.
This error is fixed in the beta release. v0.3.2-beta.3.

**Comment by CuriosusTuberosum** [comment]
@palosbuenos can confirm, thanks for the update.

**Comment by coco1602** [comment]
I'm sorry but I still have the issue even after downloading the last beta version.

**Comment by DR-3araby** [comment]
i have the same issue
